FlowFuse/installer

- README.md
> fix instructions for running install.sh

- .github/workflows/release.yml
First pass at CI for Installer
> Action to package installer zip

- .github/workflows/release.yml
Got the TAG asignment right this time
> ok, enough messing around

- .gitattributes
- README.md
- app/package.json
- bin/flowforge.bat
- install.bat
Fixes to allow Windows batch files to be double clicked on in File Explorer
Added pauses before each exit so logs can be seen.
Also fixed FLOWFORGE_HOME being set to the bin directory.
Finally fixed typos in the README.md
> Windows fixes

- README.md
- app/package.json
Also minor change to README.md to reflect correct path in the zip
file
> Update version number to 0.1.1

- README.md
update readme with additional information for windows installation
> Additional info for windows installation

- install.sh
fixes https://github.com/flowforge/flowforge/issues/245
> Fix missing space

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 0.3.0
- Update version to 0.3.0
> Release 0.3.0

- bin/ff-install-stack.bat
- bin/ff-install-stack.sh
Add scripts to install stacks into a production FlowForge LocalFS install.
Works with https://github.com/flowforge/flowforge/pull/571
> Add ff-install-stack scripts

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 0.5.0
- Update version to 0.5.0
> Release 0.5.0

- install.sh
> Ensure bin/* is executable

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 0.6.0
- Update version to 0.6.0
> Release 0.6.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 0.7.0
- Update version to 0.7.0
> Release 0.7.0

- install.sh
fixes https://github.com/flowforge/flowforge/issues/729
> Add check for build tools if NodeJS present

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 0.8.0
- Update version to 0.8.0
> Release 0.8.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 0.9.0
- Update version to 0.9.0
> Release 0.9.0

- CHANGELOG.md
> Release 0.9.1

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 0.10.0
- Update version to 0.10.0
> Release 0.10.0

- install.sh
Also add a message when complete when not on Linux.
There will be a separate issue to add support for installing stacks
> Clean up messaging around sudo

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.0.0
- Update version to 1.0.0
> Release 1.0.0

- CHANGELOG.md
- install.sh
> Fix typo in last if/else block

- README.md
- install.bat
* Set the console **TITLE** to "FlowForge Installer"
* Add MIN version check for NPM
* Silence package.lock does not exist (Check file/dir exists before  deletion)
* Silence file copy action
* Add common sections for printing nodejs & npm problems to screen 
* Add PRINT subroutine for printing consistent formatting of variable length lines of text to screen
* align to docs/install/readme PR https://github.com/flowforge/flowforge/pull/1249
---
Screenshots...
> Silence windows batch errors, update README (Developer Demo follow ups)

- .github/workflows/release.yml
> Remove version number from release zip file

- broker/mosquitto.conf
Still working on building/downloading go-auth.so for different platforms
part of #50
> Add template mosquitto.conf

- .github/workflows/release.yml
Realised the paths also had the version tags as well, this now matches the docs
> Update the path in the zip to match the docs

- install.bat
> use `call` to run ff-stack-install.bat

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.1.0
- Update version to 1.1.0
> Release 1.1.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.2.0
- Update version to 1.2.0
> Release 1.2.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.3.0
- Update version to 1.3.0
> Release 1.3.0

- README.md
> Update link to installer zip

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.4.0
- Update version to 1.4.0
> Release 1.4.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.5.0
- Update version to 1.5.0
> Release 1.5.0

- install.sh
Ensure all commands are run in the scope of the install dir even if instructions are not followed.
> Update install.sh to run in right place

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.9.0
- Update version to 1.9.0
> Release 1.9.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.10.0
- Update version to 1.10.0
> Release 1.10.0

- .github/workflows/project-automation.yml
- README.md
Update reusable workflow name and README.md
> Update references to FlowFuse

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 1.13.0
- Update version to 1.13.0
> Release 1.13.0

- CHANGELOG.md
- app/package.json
> Bump to v1.13.1

- app/package.json
> Update Forge->Fuse naming

- install.bat
- install.sh
Fix path we copy the default flowforge.yml from
> Fix path base flowforge.yml is copied from

- README.md
- app/package.json
- install.bat
- install.sh
Bump min NodeJS version to 18.x
https://github.com/FlowFuse/flowfuse/pull/3300
> Bump min NodeJS version to 18.x

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 2.0.0
- Update version to 2.0.0
> Release 2.0.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 2.1.0
- Update version to 2.1.0
> Release 2.1.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 2.4.0
- Update version to 2.4.0
> Release 2.4.0

- README.md
- install.bat
- install.sh
Bump the default installed NodeJS version to v20 in prep for Node-RED v4.0
https://app-eu1.hubspot.com/help-desk/26586079/view/233410279/ticket/3257395405/thread/3997566925#email
> Bump default installed NodeJS version

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 2.5.0
- Update version to 2.5.0
> Release 2.5.0

- CHANGELOG.md
- app/package.json
- Update CHANGELOG for 2.6.0
- Update version to 2.6.0
> Release 2.6.0

- CHANGELOG.md
- app/package.json
- **Update CHANGELOG for 2.16.0**
- **Update version to 2.16.0**
> Release 2.16.0

- CHANGELOG.md
- app/package.json
- **Update CHANGELOG for 2.17.0**
- **Update version to 2.17.0**
> Release 2.17.0

- CHANGELOG.md
- app/package.json
- **Update CHANGELOG for 2.21.0**
- **Update version to 2.21.0**
> Release 2.21.0

- CHANGELOG.md
- app/package.json
- **Update CHANGELOG for 2.22.0**
- **Update version to 2.22.0**
> Release 2.22.0
